global:
  proj: utils
  which: test

watch:
  - src
  - test/*/*.ls

rm-dist: rm -rf dist/*/*

rm-src-js: rm src/*/*.js

test.all:
  - gulp default
  - |-
    for i in test/*/*.js
    do
      node $i || exit 1
    done

test.proj:
  - gulp default 1>/dev/null
  - |-
    for i in test/{{global.proj}}/*.js
    do
      node $i || exit 1
    done

test.only:
  - gulp default
  - node ./test/{{global.proj}}/{{global.which}}.js || exit 1


gulpfile:
  watch:
    - src/gulpfile.ls
  exec-locale:
    - lsc -bco . src/gulpfile.ls
    - gulp default


dev.install:
  - npm install gulp
  - npm install livescript
  - npm install gulp-tap
  - npm install gulp-livescript
  - npm install gulp-rename
  - npm install gulp-yaml
  - npm install gulp-replace

version.update: update-version src/package.yaml hoplon