name: valleydate
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/valleydate#readme.md
license: BSD-3-Clause
description: immutable object validator
repository: https://github.com/sourcevault/valleydate.git
version: 0.1.20
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  ramda: "*"
  error-stack-parser: "*"
devDependencies:
  "gulp-livescript": "*"
  "gulp-rename": "*"
  "gulp-yaml": "*"
  livescript: "*"
  "gulp-tap": "*"
  gulp: "*"
keywords:
  - "json-schema-validator"
  - "schema-validator"
  - "error-messages"
  - "type-check"
  - "functional"
  - "validator"
  - "chainable"
  - "immutable"
  - "validate"
  - "objects"
  - "monadic"
  - "mostjs"
  - "simple"
  - "schema"
  - "types"
  - "Array"
  - "monad"
  - "JSON"